# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b99fd9b0f63d343a4e8d38593b04536416ab0fecd3f70f5684170cdf9160b97c95c41409919e390c60367756bf3a064eaf9a379f98458ab9780c629a0bdf6d18

test:
  secret_key_base: 63c55b1b64e6fdc633f8ad7894dd07f9e0befb78b0c980344b8ff511405fb1b2c00257698f9c1feb8e5218dd0f5e30784effa70a4abb64ee838bb4d6623d7a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
